### ISSUE TITLE
h36m_mosh_train.npz

### ISSUE THREAD

**Issue by youwh-PIRI** [Droliven/pymaf_reimplementation#1]
Hello, is it possible for you to send me the h36m_mosh_train.npz as well_
My email is [[2705837989@qq.com](mailto:2705837989@qq.com)])
Thanks in advance!

**Comment by youwh-PIRI** [comment]
get already

**Comment by Whiplash-18** [comment]
> get already

Hello, could you send me the h36m_mosh_train.npz , my email is 17635280135@163.com
Thank you so much!!
